name: SpyPlugin
main: io.github.MrSpy42.spyplugin.SpyPlugin
version: 0.1.4-final
api-version: 1.16
author: MrSpy42
commands:
   memuse:
      description: Prints server memory usage.
      usage: /memuse
      permission: SpyPlugin.memuse
      permission-message: You don't have permission to run this command.
   aboutspy:
      description: Prints stuff about SpyPlugin.
      usage: /aboutspy
      permission: SpyPlugin.aboutspy
      permission-message: You don't have permission.
   serverload:
      description: Prints server load percentage
      usage: /serverload
      permission: SpyPlugin.aboutspy
      permission-message: You don't have permission.
   freespace:
      description: Prints server free disk space (in MBs).
      usage: /freespace
      permission: SpyPlugin.freespace
      permission-message: You don't have permission.